// ABOUTME: Inserts a snippet into the frontmost app as an ordered plan of pasted text runs and
// ABOUTME: synthesized key-sends. Snapshots/restores the clipboard once around the whole sequence.
import AppKit
import SnipKit

final class PasteEngine {
    private let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")

    private let commandV: CGKeyCode = 0x09
    private let leftArrow: CGKeyCode = 0x7B

    /// A sequence owns the clipboard for up to ~1s while it pastes runs and sends keys.
    private var isInserting = false

    func insert(_ snippet: Snippet) {
        // A second fire mid-sequence would interleave two clipboard save/restore brackets and corrupt
        // the user's clipboard. Drop it; the ring can be fired again once this sequence finishes.
        guard !isInserting else { return }

        let pasteboard = NSPasteboard.general

        // Resolve tokens first, so {clipboard} sees the user's clipboard before we overwrite it.
        let resolver = TokenResolver(clipboard: { pasteboard.string(forType: .string) })
        let resolved = resolver.resolve(snippet.body)
        guard !resolved.steps.isEmpty else { return }

        isInserting = true
        let saved = snapshot(pasteboard)

        Task { @MainActor in
            defer { self.isInserting = false }
            var lastWriteCount = pasteboard.changeCount

            for step in resolved.steps {
                switch step {
                case .text(let text):
                    pasteboard.clearContents()
                    let item = NSPasteboardItem()
                    item.setString(text, forType: .string)
                    // Ask clipboard managers (Maccy, Paste) not to archive our snippet firings.
                    item.setData(Data(), forType: self.transientType)
                    item.setData(Data(), forType: self.autoGeneratedType)
                    pasteboard.writeObjects([item])
                    lastWriteCount = pasteboard.changeCount

                    await self.waitForCleanModifiers(timeout: 0.5)
                    self.post(key: self.commandV, flags: .maskCommand)
                    // No signal exists for "the target read the pasteboard"; a settle delay is the
                    // industry-standard imperfect answer. A synthesized key must not beat this paste.
                    try? await Task.sleep(for: .milliseconds(180))

                case .key(let key):
                    await self.waitForCleanModifiers(timeout: 0.5)
                    self.post(key: self.code(for: key))
                    try? await Task.sleep(for: .milliseconds(60))
                }
            }

            // The resolver guarantees the caret marker only survives in the final text run with no key
            // after it, so walking left from the end lands where the author placed $|.
            self.moveCaretLeft(by: resolved.caretOffsetFromEnd)

            // Restore the clipboard once, guarded on our last write so a user copy is not clobbered.
            try? await Task.sleep(for: .milliseconds(200))
            if pasteboard.changeCount == lastWriteCount {
                self.restore(saved, to: pasteboard)
            }
        }
    }

    // MARK: - Key codes

    private func code(for key: SnippetKey) -> CGKeyCode {
        switch key {
        case .enter: return 0x24   // kVK_Return
        case .tab: return 0x30     // kVK_Tab
        }
    }

    // MARK: - Pasteboard

    private func snapshot(_ pasteboard: NSPasteboard) -> [[NSPasteboard.PasteboardType: Data]] {
        guard let items = pasteboard.pasteboardItems else { return [] }
        return items.map { item in
            var contents: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types where type != concealedType {
                if let data = item.data(forType: type) { contents[type] = data }
            }
            return contents
        }
    }

    private func restore(_ saved: [[NSPasteboard.PasteboardType: Data]], to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        let items: [NSPasteboardItem] = saved.compactMap { contents in
            guard !contents.isEmpty else { return nil }
            let item = NSPasteboardItem()
            for (type, data) in contents { item.setData(data, forType: type) }
            return item
        }
        guard !items.isEmpty else { return }
        pasteboard.writeObjects(items)
    }

    // MARK: - Synthetic input

    private func post(key: CGKeyCode, flags: CGEventFlags = []) {
        let source = CGEventSource(stateID: .combinedSessionState)
        let down = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: false)
        down?.flags = flags
        up?.flags = flags
        stamp(down)
        stamp(up)
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }

    private func stamp(_ event: CGEvent?) {
        event?.setIntegerValueField(.eventSourceUserData, value: EventTapEngine.magicUserData)
    }

    /// Offsets are grapheme clusters because Cocoa moves the caret one grapheme per arrow press.
    private func moveCaretLeft(by graphemes: Int) {
        guard graphemes > 0 else { return }
        for _ in 0..<graphemes { post(key: leftArrow) }
    }

    /// A physically-held modifier can turn our synthetic Cmd-V into Opt-Cmd-V, which in Finder
    /// means "Move Item Here". Wait until the user's modifiers are released before each synthetic key.
    private func waitForCleanModifiers(timeout: TimeInterval) async {
        let watched: CGEventFlags = [.maskCommand, .maskShift, .maskAlternate, .maskControl]
        let deadline = Date().addingTimeInterval(timeout)
        while Date() < deadline {
            let flags = CGEventSource.flagsState(.combinedSessionState)
            if flags.intersection(watched).isEmpty { return }
            try? await Task.sleep(for: .milliseconds(10))
        }
    }
}
