// ABOUTME: Inserts snippet text into the frontmost app via paste-and-restore plus caret repositioning.
// ABOUTME: Snapshots and restores the clipboard (changeCount-guarded) and marks its writes transient.
import AppKit
import SnipKit

final class PasteEngine {
    private let transientType = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    private let autoGeneratedType = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    private let concealedType = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")

    private let commandV: CGKeyCode = 0x09
    private let leftArrow: CGKeyCode = 0x7B

    func insert(_ snippet: Snippet) {
        let pasteboard = NSPasteboard.general

        // Resolve tokens first, so {clipboard} sees the user's clipboard before we overwrite it.
        let resolver = TokenResolver(clipboard: { pasteboard.string(forType: .string) })
        let resolved = resolver.resolve(snippet.body)

        let saved = snapshot(pasteboard)

        pasteboard.clearContents()
        let item = NSPasteboardItem()
        item.setString(resolved.text, forType: .string)
        // Ask clipboard managers (Maccy, Paste) not to archive our snippet firings.
        item.setData(Data(), forType: transientType)
        item.setData(Data(), forType: autoGeneratedType)
        pasteboard.writeObjects([item])
        let writeCount = pasteboard.changeCount

        waitForCleanModifiers(timeout: 0.5)
        post(key: commandV, flags: .maskCommand)

        // The paste is handled as a menu action inside the target app and can complete after
        // immediately-queued arrows, which would move the caret before the text exists.
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.12) {
            self.moveCaretLeft(by: resolved.caretOffsetFromEnd)
        }

        // There is no signal for "the target finished reading the pasteboard", so this delay is
        // the industry-standard imperfect answer. Guard on changeCount so a user copy is not clobbered.
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.35) {
            guard pasteboard.changeCount == writeCount else { return }
            self.restore(saved, to: pasteboard)
        }
    }

    // MARK: - Pasteboard

    private func snapshot(_ pasteboard: NSPasteboard) -> [[NSPasteboard.PasteboardType: Data]] {
        guard let items = pasteboard.pasteboardItems else { return [] }
        return items.map { item in
            var contents: [NSPasteboard.PasteboardType: Data] = [:]
            for type in item.types where type != concealedType {
                if let data = item.data(forType: type) { contents[type] = data }
            }
            return contents
        }
    }

    private func restore(_ saved: [[NSPasteboard.PasteboardType: Data]], to pasteboard: NSPasteboard) {
        pasteboard.clearContents()
        let items: [NSPasteboardItem] = saved.compactMap { contents in
            guard !contents.isEmpty else { return nil }
            let item = NSPasteboardItem()
            for (type, data) in contents { item.setData(data, forType: type) }
            return item
        }
        guard !items.isEmpty else { return }
        pasteboard.writeObjects(items)
    }

    // MARK: - Synthetic input

    private func post(key: CGKeyCode, flags: CGEventFlags = []) {
        let source = CGEventSource(stateID: .combinedSessionState)
        let down = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: true)
        let up = CGEvent(keyboardEventSource: source, virtualKey: key, keyDown: false)
        down?.flags = flags
        up?.flags = flags
        stamp(down)
        stamp(up)
        down?.post(tap: .cghidEventTap)
        up?.post(tap: .cghidEventTap)
    }

    private func stamp(_ event: CGEvent?) {
        event?.setIntegerValueField(.eventSourceUserData, value: EventTapEngine.magicUserData)
    }

    /// Offsets are grapheme clusters because Cocoa moves the caret one grapheme per arrow press.
    private func moveCaretLeft(by graphemes: Int) {
        guard graphemes > 0 else { return }
        for _ in 0..<graphemes { post(key: leftArrow) }
    }

    /// A physically-held modifier can turn our synthetic Cmd-V into Opt-Cmd-V, which in Finder
    /// means "Move Item Here". Wait until the user's modifiers are released.
    private func waitForCleanModifiers(timeout: TimeInterval) {
        let watched: CGEventFlags = [.maskCommand, .maskShift, .maskAlternate, .maskControl]
        let deadline = Date().addingTimeInterval(timeout)
        while Date() < deadline {
            let flags = CGEventSource.flagsState(.combinedSessionState)
            if flags.intersection(watched).isEmpty { return }
            usleep(10_000)
        }
    }
}
